# Generated by Django 4.1.4 on 2024-07-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='https://studyways.storage.iran.liara.space/media/blog_cover'),
        ),
    ]
